### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by viktormalik**
Changelog:
- Allow creating snapshots from a single C source file
- Add extended analysis statistics
- New pattern for matching reordered binary operations
- New pattern for variable grouping
- Nix flakes support for building and development
- Unification of applied optimizations for various build commands
- Fix comparison of PHI nodes and union types

### CODE REVIEW

**Comment by viktormalik** [comment]
Unfortunately, we still don't support LLVM 17 so we won't be able to build this release to newer Fedora versions. Still, I'd do the release since there's a lot of new changes coming. We may still do a feature release once we add the LLVM support.

**Comment by viktormalik** [comment]
> The version number should probably be changed also here
> 
> https://github.com/diffkemp/diffkemp/blob/e6cded9aefd2e51ada26c972f499fe08d442d789/flake.nix#L20
> 

Nice catch! Fixed.

> , otherwise I think we can do the release.
> Originally, I encountered two problems when I tried the current (respectively previous) RPM package on Fedora, but after further investigation it should be fine:
> [...]

If you wouldn't mind, I'll ping you when the new RPMs are ready and you could test if the above issues are resolved.

**Review by PLukas2018 — APPROVED** [review]

**Comment by PLukas2018** [comment]
> If you wouldn't mind, I'll ping you when the new RPMs are ready and you could test if the above issues are resolved.

Sure, I can test it.

**Comment by viktormalik** [comment]
@PLukas2018 here's the list of artifacts from the newest RPM scratch build (for Fedora 39, i.e. LLVM 17):

https://download.copr.fedorainfracloud.org/results/viktormalik/diffkemp/fedora-39-x86_64/07475809-diffkemp/

If you could try to download the RPM, install it, and check if the errors that you previously encountered disappeared, that would be great. I had to do some changes to the specfile, see #339 (these are already included in the above scratch build).

Thanks!

**Comment by PLukas2018** [comment]
> If you could try to download the RPM, install it, and check if the errors that you previously encountered disappeared, that would be great. I had to do some changes to the specfile, see #339 (these are already included in the above scratch build).

So I tried it (I tried `build`, `build-kernel`, `view` commands) and did not find any problem, everything worked well.

**Comment by viktormalik** [comment]
Thanks! v0.6.0 is out:

https://github.com/diffkemp/diffkemp/releases/tag/v0.6.0

**Pull request merged**
